### PR TITLE
 BugFix: Reimplement getHostStatus using Socket API

### PR DESCRIPTION
**Pull request by josealf**
Testing scheduled tasks, I found connections using telnet were failing most of the time with error "Error:Connection refused" . Debugging pointed to getHostStatus() that is called before connection to the device. It turns out our, getHostStatus is using fsockopen to verify connectivity, but it fails to close the socket. I tested adding fclose(fp), but it did not solve the problem. It turns out, sockets are not closed inmmediatley and a work around must be implemented as documented in user notes in http://php.net/manual/en/function.socket-close.php
I also fixed the comments.

### CODE REVIEW

**Comment by josealf** [comment]
Please review the getHostStatus re-implementation. This avoids fsockopen Error:Connection refused (111)

**Comment by rconfig** [comment]
Hey,

No issues with this change. Need to merge but same as other pull. Need CHANGELOG update. And lets may use this for merge and delete the other commit.

Thanks again

**Comment by josealf** [comment]
Steph,

CHANGELOG updated as requested. Also made comments more accurate in files calling getHostStatus. Let me know if this suits. 

Thanks.

**Comment by rconfig** [comment]
perfect, thanks. will merge today

**Pull request merged**
