### PR TITLE
Bug in showCmdScript.php - $status will never match

### PR DESCRIPTION
**Pull request by josealf**
$status will never be equal to `'<font color=red>Unavailable</font>'` because getHostStatus() returns `'<font color="red">Unavailable</font>'`

### CODE REVIEW

**Comment by josealf** [comment]
Stephen, please review.

**Comment by josealf** [comment]
This is similar to 1b942fd, but for downloadNowScript.php

**Comment by josealf** [comment]
These are similar to 1b942fd to apply the same change to two mode files configCategoryScript.php and configDeviceScript.php.

**Comment by rconfig** [comment]
Thanks Jose, for this commit, can you update the CHANGELOG before I merge it. Just create a new version section 3.6.8 and add the 'fixed' line per previous format. 

Thanks for fixing

**Pull request closed without merging**
